#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pytz-deprecation-shim
Version  : 0.1.0.post0
Release  : 1
URL      : https://files.pythonhosted.org/packages/94/f0/909f94fea74759654390a3e1a9e4e185b6cd9aa810e533e3586f39da3097/pytz_deprecation_shim-0.1.0.post0.tar.gz
Source0  : https://files.pythonhosted.org/packages/94/f0/909f94fea74759654390a3e1a9e4e185b6cd9aa810e533e3586f39da3097/pytz_deprecation_shim-0.1.0.post0.tar.gz
Summary  : Shims to make deprecation of pytz easier
Group    : Development/Tools
License  : Apache-2.0
Requires: pytz-deprecation-shim-license = %{version}-%{release}
Requires: pytz-deprecation-shim-python = %{version}-%{release}
Requires: pytz-deprecation-shim-python3 = %{version}-%{release}
Requires: python-dateutil
Requires: tzdata
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dateutil
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : tzdata
BuildRequires : virtualenv
BuildRequires : wheel

%description
===========================================================
        
        ``pytz`` has served the Python community well for many years, but it is no
        longer the best option for providing time zones. ``pytz`` has a non-standard
        interface that is `very easy to misuse

%package license
Summary: license components for the pytz-deprecation-shim package.
Group: Default

%description license
license components for the pytz-deprecation-shim package.


%package python
Summary: python components for the pytz-deprecation-shim package.
Group: Default
Requires: pytz-deprecation-shim-python3 = %{version}-%{release}

%description python
python components for the pytz-deprecation-shim package.


%package python3
Summary: python3 components for the pytz-deprecation-shim package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pytz-deprecation-shim package.


%prep
%setup -q -n pytz_deprecation_shim-0.1.0.post0
cd %{_builddir}/pytz_deprecation_shim-0.1.0.post0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1636498705
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pytz-deprecation-shim
cp %{_builddir}/pytz_deprecation_shim-0.1.0.post0/LICENSE %{buildroot}/usr/share/package-licenses/pytz-deprecation-shim/a17821d024ce62859b8750020c3b7cbb2e6a57af
cp %{_builddir}/pytz_deprecation_shim-0.1.0.post0/licenses/LICENSE_APACHE %{buildroot}/usr/share/package-licenses/pytz-deprecation-shim/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
python3 -m install --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pytz-deprecation-shim/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/pytz-deprecation-shim/a17821d024ce62859b8750020c3b7cbb2e6a57af

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
